[custom] New check on bundle feature.xml file
openhab/static-code-analysis pull request #395
Opened 2020-09-24 15:44 UTC by Hilbrand

2021-01-08 08:32 UTC, Hilbrand commented
:tada: builds again. @wborn can I persuade you to have a look :smile:

2021-01-08 21:19 UTC, wborn requested changes
Thanks for adding this useful check @Hilbrand! It will certainly help with reducing issues in the features. I have few minor comments below.

2021-01-08 21:19 UTC, wborn commented on custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java
> +    private String adapatedFeatureName(String artifactId) {
```suggestion
    private String adaptedFeatureName(String artifactId) {
```

2021-01-08 21:19 UTC, wborn commented on custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java
> +        final String featureName = adapatedFeatureName(artifactId);
```suggestion
        final String featureName = adaptedFeatureName(artifactId);
```

2021-01-08 21:19 UTC, wborn commented on custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafAddonFeatureCheckTest.java
> +@RunWith(MockitoJUnitRunner.class)
This is for JUnit 4 and I don't see any `@Mock`s?

```suggestion
```

2021-01-10 15:31 UTC, wborn approved these changes

2021-01-10 15:41 UTC, merged